//===-- FunGTOps.td - Python bindings for fungt --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===---------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_FUNGT_OPS
#define PYTHON_BINDINGS_FUNGT_OPS

include "FunGT/FunGTOps.td"

#endif
